### ISSUE TITLE
denominator 4.5 not compiled for java 1.6.0_65

### ISSUE THREAD

**Issue by quinncomendant** [Netflix/denominator#367]
I tried updating to denominator 4.5 today via homebrew. The new version doesn't run on the version of JDK in OS X 10.9.5 Mavericks:

    Exception in thread "main" java.lang.UnsupportedClassVersionError: io/airlift/airline/Cli : Unsupported major.minor version 51.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    	at denominator.cli.Denominator.main(Denominator.java:115)

Mavericks version of java:

    [q@haywire/0 ~] java -version
    java version "1.6.0_65"
    Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
    Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

http://stackoverflow.com/a/11432195/277303 describes how to fix the problem.

**Comment by rspieldenner** [comment]
Java 6 (as of Feb 2013) and 7 (as of Apr 2015) are both EOL and receive no
more security updates. Some of our libraries will use java 7 and java 8
features and will move forward. Each repo owner will decide when to drop
support for java 6 and java 7. To use homebrew to get a new Java.



brew install caskroom/cask/brew-cask

brew cask install java

**Comment by quinncomendant** [comment]
Yep, that sounds like the right thing to do. Thanks for the fast reply. 😊
